name: Rust Testing
run-name: ${{ github.actor }} is testing Rust code
on: [push, pull_request]
jobs:
  Test-Rust-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Navigate to directory
        run: cd poker

      - name: Install dependencies
        run: cargo fetch

      - name: Run tests
        run: cargo test --verbose
